# Generated by Django 5.0.2 on 2024-04-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='preview_images/'),
        ),
    ]
