# Generated by Django 5.0.2 on 2024-04-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_pdfdocument_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='preview_image',
        ),
    ]
